Metadata:
  GhaStack:
    localTemplateFile: &gha_deploy_template_body ./stacksets/gha-deploy/stackset.yaml
  CfnCrStack:
    localTemplateFile: &cfn_cr_template_body ./stacksets/cfn-custom-resource-deploy/stackset.yaml

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS account infrastructure stackset (GHA Deployments)

Parameters:
  TargetOuIds:
    Type: CommaDelimitedList
    Description: List of OUs
  TargetRegions:
    Type: CommaDelimitedList
    Description: Regions to deploy to
  CicdAwsAccountId:
    Type: String
    Description: AWS Account ID for CI/CD
  DeployBucketArn:
    Type: String
    Description: S3 bucket ARN for deployment
  CustomResourceSsmParamName:
    Type: String
    Description: SSM parameter name for custom resource
  CustomResourceTopicName:
    Type: String
    Description: Custom resource ARN


Resources:
  OrgCiCdGhaDeploy:
    Type: AWS::CloudFormation::StackSet
    Properties:
      StackSetName: CiCdGhaDeploy
      Description: GHA CI/CD Deployment
      Parameters:
        - ParameterKey: CicdAwsAccountId
          ParameterValue: !Ref CicdAwsAccountId
        - ParameterKey: DeployBucketArn
          ParameterValue: !Ref DeployBucketArn
      Capabilities:
        - CAPABILITY_NAMED_IAM
      StackInstancesGroup:
        - DeploymentTargets:
            OrganizationalUnitIds: !Ref TargetOuIds
          Regions: !Ref TargetRegions
      AutoDeployment:
        Enabled: true
        RetainStacksOnAccountRemoval: false
      ManagedExecution:
        Active: true
      OperationPreferences:
        RegionConcurrencyType: PARALLEL
        FailureToleranceCount: 1
        MaxConcurrentCount: 5
      PermissionModel: SERVICE_MANAGED
      TemplateBody: *gha_deploy_template_body

  DeployAccountCfnCustomResourcesSupport:
    Type: AWS::CloudFormation::StackSet
    Properties:
      StackSetName: OrgDeployAccountCfnCustomResourcesSupport
      Description: Provides service discovery for AWS CFN Custom Resources
      Parameters:
        - ParameterKey: CustomResourceSsmParamName
          ParameterValue: !Ref CustomResourceSsmParamName
        - ParameterKey: CustomResourceTopicName
          ParameterValue: !Ref CustomResourceTopicName
        - ParameterKey: CicdAwsAccountId
          ParameterValue: !Ref CicdAwsAccountId
      StackInstancesGroup:
        - DeploymentTargets:
            OrganizationalUnitIds: !Ref TargetOuIds
          Regions: !Ref TargetRegions
      AutoDeployment:
        Enabled: true
        RetainStacksOnAccountRemoval: false
      ManagedExecution:
        Active: true
      OperationPreferences:
        RegionConcurrencyType: PARALLEL
        FailureToleranceCount: 1
        MaxConcurrentCount: 5
      PermissionModel: SERVICE_MANAGED
      TemplateBody: *cfn_cr_template_body
