AWSTemplateFormatVersion: '2010-09-09'
Transform:
  - 'AWS::Serverless-2016-10-31'
Description: GitHib Actions integration stacks

Parameters:
  TargetOuIds:
    Type: String
    Description: Comma separated listist of OUs
  TargetRegions:
    Type: String
    Description: Comma separated list of regions
  AwsOrganizationId:
    Type: String
    Description: AWS Organization ID
  CicdAwsAccountId:
    Type: String
    Description: AWS Account ID for CI/CD
  CiCdOuIds:
    Type: String
    Description: Comma separated listist of OUs

Resources:
  GhaBuildStackSet:
    Type: AWS::Serverless::Application
    Properties:
      Location: './stacksets/gha-build/stackset.yaml'
      Parameters:
        TargetOuIds: !Ref CiCdOuIds
        TargetRegions: !Ref TargetRegions
        AwsOrganizationId: !Ref AwsOrganizationId
