AWSTemplateFormatVersion: '2010-09-09'
Transform:
  - 'AWS::Serverless-2016-10-31'
Description: AWS GitHib Actions integration stacks

Parameters:
  TargetOuIds:
    Type: String
    Description: Comma separated listist of OUs
  TargetRegions:
    Type: String
    Description: Comma separated list of regions
  AwsOrganizationId:
    Type: String
    Description: AWS Organization ID
  CicdAwsAccountId:
    Type: String
    Description: AWS Account ID for CI/CD

Resources:
  StacksetTemplateBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-stacksets-${AWS::AccountId}-${AWS::Region}"

  GhaBuildStackSet:
    Type: AWS::Serverless::Application
    Properties:
      Location: './stacksets/gha-build/stackset.yaml'
      Parameters:
        StacksetTemplateBucket: !Ref StacksetTemplateBucket
        TargetOuIds: !Ref TargetOuIds
        TargetRegions: !Ref TargetRegions
        AwsOrganizationId: !Ref AwsOrganizationId

  GhaDeployStackSet:
    Type: AWS::Serverless::Application
    DependsOn: GhaBuildStackSet   # Need build role to pre-exist or validation during deploy fails.
    Properties:
      Location: './stacksets/gha-deploy/stackset.yaml'
      Parameters:
        StacksetTemplateBucket: !Ref StacksetTemplateBucket
        TargetOuIds: !Ref TargetOuIds
        TargetRegions: !Ref TargetRegions
        CicdAwsAccountId: !Ref CicdAwsAccountId
        DeployBucketArn: !Sub 'arn:aws:s3:::aws-sam-cli-sourcebucket-${CicdAwsAccountId}-us-east-1'

  GhaDeployStackManagement:
    Type: AWS::Serverless::Application
    DependsOn: GhaBuildStackSet   # Need build role to pre-exist or validation during deploy fails.
    Properties:
      Location: './stacksets/gha-deploy/template.yaml'
      Parameters:
        CicdAwsAccountId: !Ref CicdAwsAccountId
        DeployBucketArn: !Sub 'arn:aws:s3:::aws-sam-cli-sourcebucket-${CicdAwsAccountId}-us-east-1'
