
Metadata:
  GhaStack:
    localTemplateFile: &gha_template_body ./template.yaml
  SamStack:
    localTemplateFile: &sam_template_body ./sam-deployment.yaml

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS account infrastructure stackset (GHA Build)

Parameters:
  TargetOuIds:
    Type: CommaDelimitedList
    Description: List of OUs
  TargetRegions:
    Type: CommaDelimitedList
    Description: Regions to deploy to
  AwsOrganizationId:
    Type: String
    Description: AWS Organization ID

Resources:
  OrgCiCdSamArtifacts:
    Type: AWS::CloudFormation::StackSet
    Properties:
      StackSetName: CiCdSamArtifacts
      Description: AWS SAM Deployment
      CallAs: DELEGATED_ADMIN
      Parameters:
        - ParameterKey: AwsOrganizationId
          ParameterValue: !Ref AwsOrganizationId
        - ParameterKey: BuildAccount
          ParameterValue: 'true'
      #StackInstancesGroup:
      #  - DeploymentTargets:
      #      OrganizationalUnitIds: !Ref TargetOuIds
      #    Regions: !Ref TargetRegions
      AutoDeployment:
        Enabled: true
        RetainStacksOnAccountRemoval: false
      ManagedExecution:
        Active: true
      OperationPreferences:
        RegionConcurrencyType: PARALLEL
        FailureToleranceCount: 1
        MaxConcurrentCount: 5
      PermissionModel: SERVICE_MANAGED
      TemplateBody: *sam_template_body

  OrgCiCdGhaBuild:
    Type: AWS::CloudFormation::StackSet
    DependsOn: OrgCiCdSamArtifacts
    Properties:
      StackSetName: CiCdGhaBuild
      Description: GHA CI/CD Deployment Build
      CallAs: DELEGATED_ADMIN
      Parameters:
        - ParameterKey: DeployBucketArn
          ParameterValue: '/org/cicd/SamDeployBucketArn'
      #StackInstancesGroup:
      #  - DeploymentTargets:
      #      OrganizationalUnitIds: !Ref TargetOuIds
      #    Regions: !Ref TargetRegions
      Capabilities:
        - CAPABILITY_NAMED_IAM
      AutoDeployment:
        Enabled: true
        RetainStacksOnAccountRemoval: false
      ManagedExecution:
        Active: true
      OperationPreferences:
        RegionConcurrencyType: PARALLEL
        FailureToleranceCount: 1
        MaxConcurrentCount: 5
      PermissionModel: SERVICE_MANAGED
      TemplateBody: *gha_template_body
